name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"     # jalan tiap 07:00 WIB
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Generate 2 file SVG (mode terang & gelap)
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{erycaaaaa}}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      # Deploy hasil ke branch "output"
      - name: Deploy to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
